name: deploy to s3

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.4.0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install packages
        run: yarn install

      - name: Genarate files
        env:
          VUE_APP_USER_API_ENDPOIT: 'https://ambitious.eks-nigoroku.net:4431'
          VUE_APP_TODO_API_ENDPOIT: 'https://ambitious.eks-nigoroku.net:4432'
          VUE_APP_ACHIEVEMENT_API_ENDPOIT: 'https://ambitious.eks-nigoroku.net:4433'
          VUE_APP_BOADLIST_API_ENDPOIT: 'https://ambitious.eks-nigoroku.net:4434'
        run: yarn generate

      - name: Upload dist files to S3
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: aws s3 sync ./dist s3://$S3_BUCKET_NAME/ --quiet
